'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {apiFetch,token} from '../../lib/api';

type Template={name:string;icon:string;title:string;prompt:string;platform:string;ratio:string;dialect:string;style:string;duration:number};
const templates:Template[]=[
 {name:'Local Business Reel',icon:'🏪',title:'Local business promo',prompt:'Create a fast Hindi/Hinglish promotional reel for a local Indian business. Open with a strong visual hook, show the offer clearly, add one funny relatable moment, and end with a direct WhatsApp/visit CTA.',platform:'instagram_reel',ratio:'9:16',dialect:'hinglish',style:'business_funny',duration:30},
 {name:'Kanpuri Comedy',icon:'😂',title:'Kanpuri comedy episode',prompt:'Babuji, Guddu and Bittu get into a fresh Kanpuriya comedy situation around a new AI gadget. Use natural Kanpuriya rhythm, physical comedy, a running joke, frequent punchlines and a twist ending.',platform:'youtube',ratio:'16:9',dialect:'kanpuriya',style:'kanpuri_comedy',duration:120},
 {name:'Product Ad',icon:'🛍️',title:'AI product ad',prompt:'Create a conversion-focused product video for Indian buyers. Start with the pain point, demonstrate the product benefit visually, show proof/value, and finish with a clear purchase CTA.',platform:'instagram_reel',ratio:'9:16',dialect:'hinglish',style:'product_ad',duration:30},
 {name:'YouTube Story',icon:'▶️',title:'YouTube story video',prompt:'Create an engaging Indian-language YouTube story with a hook in the first 5 seconds, escalating scenes, clear visual actions, retention beats every 15-20 seconds and a satisfying twist ending.',platform:'youtube',ratio:'16:9',dialect:'standard_hindi',style:'creator_story',duration:180},
];

export default function CreatePage(){
 const router=useRouter(); useEffect(()=>{if(!token()) location.href='/login?next=/create'},[]); const[msg,setMsg]=useState(''); const[busy,setBusy]=useState(false);
 const[title,setTitle]=useState('Kanpuri AI Comedy Reel'); const[prompt,setPrompt]=useState('Babuji discovers an AI ordering kiosk at a Kanpur restaurant and thinks it is the new manager. Make it fast, funny, visual and end with a twist.');
 const[platform,setPlatform]=useState('instagram_reel'); const[ratio,setRatio]=useState('9:16'); const[language,setLanguage]=useState('hi-IN'); const[dialect,setDialect]=useState('kanpuriya'); const[style,setStyle]=useState('kanpuri_comedy'); const[quality,setQuality]=useState('balanced'); const[duration,setDuration]=useState(30);
 const estimate=useMemo(()=>Math.max(4,Math.ceil(duration/8)*(quality==='premium'?12:quality==='balanced'?7:4)),[duration,quality]);
 function applyTemplate(t:Template){setTitle(t.title);setPrompt(t.prompt);setPlatform(t.platform);setRatio(t.ratio);setDialect(t.dialect);setStyle(t.style);setDuration(t.duration);}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const payload={title,prompt,platform,language,dialect,duration_seconds:Number(duration),quality,style,aspect_ratio:ratio};try{const r=await apiFetch('/v1/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const project=await r.json();if(!r.ok)throw new Error(JSON.stringify(project));const j=await apiFetch(`/v1/projects/${project.id}/generate`,{method:'POST'});const job=await j.json();if(!j.ok)throw new Error(JSON.stringify(job));router.push(`/projects/${project.id}?job=${job.id}`)}catch(err){setMsg(`Error: ${String(err)}`)}finally{setBusy(false)}}
 return <div className="createV5">
  <section className="createMain"><span className="eyebrow">CREATE • V0.8</span><h1 className="bigTitle">Turn an idea into an editable video.</h1><p className="lead">Start from a proven format or write your own prompt. Story planning stays local; expensive AI video providers remain opt-in.</p>
   <div className="templateStrip">{templates.map(t=><button type="button" key={t.name} onClick={()=>applyTemplate(t)} className="templateCard"><span>{t.icon}</span><b>{t.name}</b><small>{t.duration}s • {t.ratio}</small></button>)}</div>
   <form className="creatorForm creatorFormV5" onSubmit={submit}>
    <div className="field"><label>Project name</label><input required value={title} onChange={e=>setTitle(e.target.value)}/></div>
    <div className="field"><label>Describe the outcome</label><textarea required value={prompt} onChange={e=>setPrompt(e.target.value)}/><div className="promptHints"><span>Strong hook</span><span>Visible action</span><span>Clear CTA/twist</span></div></div>
    <div className="formGrid three"><div className="field"><label>Platform</label><select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="instagram_reel">Instagram Reel</option><option value="youtube_short">YouTube Short</option><option value="youtube">YouTube Long-form</option></select></div><div className="field"><label>Canvas</label><select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="9:16">Vertical 9:16</option><option value="16:9">Landscape 16:9</option></select></div><div className="field"><label>Duration</label><input type="number" min="5" max="600" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div></div>
    <div className="formGrid three"><div className="field"><label>Language</label><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="hi-IN">Hindi</option><option value="en-IN">English India</option></select></div><div className="field"><label>Dialect</label><select value={dialect} onChange={e=>setDialect(e.target.value)}><option value="kanpuriya">Kanpuriya</option><option value="hinglish">Hinglish</option><option value="standard_hindi">Standard Hindi</option></select></div><div className="field"><label>Style</label><select value={style} onChange={e=>setStyle(e.target.value)}><option value="kanpuri_comedy">Kanpuri Comedy</option><option value="business_funny">Business Funny</option><option value="product_ad">Product Ad</option><option value="creator_story">Creator Story</option></select></div></div>
    <div className="qualityPicker"><button type="button" onClick={()=>setQuality('economy')} className={quality==='economy'?'selected':''}><b>Economy</b><small>Local-first</small></button><button type="button" onClick={()=>setQuality('balanced')} className={quality==='balanced'?'selected':''}><b>Balanced</b><small>Recommended</small></button><button type="button" onClick={()=>setQuality('premium')} className={quality==='premium'?'selected':''}><b>Premium</b><small>Provider-ready</small></button></div>
    <div className="createSummary"><div><span>Estimated planning/media budget</span><b>~{estimate} credits</b></div><div><span>External AI video</span><b className="green">OFF by default</b></div><div><span>Render safety</span><b className="green">V6.6 timing + V0.8 cast lock</b></div></div>
    <button className="primaryButton jumbo" disabled={busy}>{busy?'Planning your story…':'✦ Generate story + editable scenes'}</button>{msg&&<p className="errorBox">{msg}</p>}
   </form>
  </section>
  <aside className="createAside"><div className="tipCard v5"><span className="eyebrow">WHAT HAPPENS NEXT</span><h3>Editable first. Render later.</h3><div className="stepMini"><b>01</b><span>Ollama creates hook, scenes and dialogue.</span></div><div className="stepMini"><b>02</b><span>Timing QA flags speech-heavy scenes before Blender.</span></div><div className="stepMini"><b>03</b><span>V6.8 trims TTS edges, adapts scene duration and removes fixed scene gaps.</span></div><div className="stepMini"><b>04</b><span>Regenerate one scene, not the whole video.</span></div></div></aside>
 </div>
}
