'use client';
import {use,useCallback,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {apiFetch,token} from '../../../lib/api';

type Scene={id:string;order_index:number;duration_seconds:number;dialogue:string;visual_prompt:string;generation_mode:string;asset_url?:string|null;metadata_json?:Record<string,any>};
type Artifact={id:string;kind:string;url:string;metadata_json?:Record<string,any>};
type MediaAsset={id:string;project_id:string;scene_id?:string|null;kind:string;provider:string;status:string;url:string;cost_credits:number;metadata_json?:Record<string,any>};
type Project={id:string;title:string;prompt:string;platform:string;language:string;dialect:string;style:string;duration_seconds:number;aspect_ratio:string;quality:string;status:string;estimated_credits:number;scenes:Scene[];artifacts:Artifact[];media_assets:MediaAsset[]};
type JobEvent={id:string;status:string;progress:number;stage:string;error?:string|null};
type Timing={status:string;total_requested_seconds:number;total_recommended_seconds:number;scenes:Array<{scene_id:string;scene_number:number;requested_seconds:number;recommended_seconds:number;delta_seconds:number;status:string}>};

function SceneCard({scene,onChanged,timing}:{scene:Scene;onChanged:()=>void;timing?:any}){
 const[dialogue,setDialogue]=useState(scene.dialogue);const[visual,setVisual]=useState(scene.visual_prompt);const[mode,setMode]=useState(scene.generation_mode);const[duration,setDuration]=useState(scene.duration_seconds);const[instruction,setInstruction]=useState('Make the punchline stronger and add a clearer physical action.');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 useEffect(()=>{setDialogue(scene.dialogue);setVisual(scene.visual_prompt);setMode(scene.generation_mode);setDuration(scene.duration_seconds)},[scene]);
 async function save(){setBusy(true);setMessage('');try{const r=await apiFetch(`/v1/scenes/${scene.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({dialogue,visual_prompt:visual,generation_mode:mode,duration_seconds:Number(duration)})});const body=await r.json();if(!r.ok)throw new Error(JSON.stringify(body));setMessage('Scene saved');onChanged()}catch(e){setMessage(`Error: ${String(e)}`)}finally{setBusy(false)}}
 async function regenerate(){setBusy(true);setMessage('AI rewriting scene…');try{const r=await apiFetch(`/v1/scenes/${scene.id}/regenerate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instruction})});const body=await r.json();if(!r.ok)throw new Error(JSON.stringify(body));setDialogue(body.dialogue);setVisual(body.visual_prompt);setMode(body.generation_mode);setDuration(body.duration_seconds);setMessage('AI rewrite complete');onChanged()}catch(e){setMessage(`Error: ${String(e)}`)}finally{setBusy(false)}}
 const risk=timing?.status==='RISK';
 return <article className="sceneStudioCard"><header><div><span className="sceneNo">SCENE {scene.order_index+1}</span><h3>{scene.metadata_json?.setup||`Scene ${scene.order_index+1}`}</h3></div><span className={risk?'timingRisk':'timingOk'}>{risk?`Needs ${timing.recommended_seconds}s`:'Timing OK'}</span></header><div className="sceneForm"><div className="field"><label>Dialogue</label><textarea value={dialogue} onChange={e=>setDialogue(e.target.value)}/></div><div className="field"><label>Visual prompt</label><textarea className="compactArea" value={visual} onChange={e=>setVisual(e.target.value)}/></div><div className="sceneControls"><div className="field"><label>Duration</label><input type="number" step="0.1" min="2" max="30" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div><div className="field"><label>Generator</label><select value={mode} onChange={e=>setMode(e.target.value)}><option>BLENDER_3D</option><option>TEMPLATE</option><option>AI_IMAGE</option><option>AI_VIDEO</option></select></div><button disabled={busy} className="secondaryButton" onClick={save}>Save</button></div><div className="aiBar"><input value={instruction} onChange={e=>setInstruction(e.target.value)}/><button disabled={busy} onClick={regenerate}>✦ Regenerate scene</button></div>{message&&<p className={message.startsWith('Error')?'errorText':'successText'}>{message}</p>}</div></article>
}

export default function ProjectDetail({params}:{params:Promise<{id:string}>}){
 const{id}=use(params); useEffect(()=>{if(!token()) location.href='/login?next='+encodeURIComponent(location.pathname)},[]);const search=useSearchParams();const[project,setProject]=useState<Project|null>(null);const[error,setError]=useState('');const[job,setJob]=useState<JobEvent|null>(null);const[engine,setEngine]=useState<any>(null);const[timing,setTiming]=useState<Timing|null>(null);const[busy,setBusy]=useState(false);const[tab,setTab]=useState<'studio'|'media'|'render'|'diagnostics'>('studio');
 const load=useCallback(async()=>{try{const [p,t]=await Promise.all([apiFetch(`/v1/projects/${id}`,{cache:'no-store'}),apiFetch(`/v1/projects/${id}/timing`,{cache:'no-store'})]);const pb=await p.json();if(!p.ok)throw new Error(JSON.stringify(pb));setProject(pb);if(t.ok)setTiming(await t.json());setError('')}catch(e){setError(String(e))}},[id]);
 useEffect(()=>{load(); apiFetch('/v1/engine/health').then(r=>r.json()).then(setEngine).catch(()=>{})},[load]);
 const watchJob=useCallback((jobId:string)=>{setJob({id:jobId,status:'QUEUED',progress:0,stage:'queued'});const timer=setInterval(async()=>{try{const r=await apiFetch(`/v1/jobs/${jobId}`);const b=await r.json();if(!r.ok)throw new Error(b.detail||'Job check failed');const progress=b.progress||0;const status=String(b.status);const stage=status==='FAILED'?'failed':status==='SUCCEEDED'?'complete':progress<10?'queued':progress<35?'planning':progress<90?'rendering':'finalizing';setJob({...b,stage});if(status==='SUCCEEDED'||status==='FAILED'){clearInterval(timer);load()}}catch{clearInterval(timer)}},900);return {close:()=>clearInterval(timer)}},[load]);
 useEffect(()=>{const initial=search.get('job');if(initial){const es=watchJob(initial);return()=>es.close()}},[search,watchJob]);
 async function postJob(path:string,body?:any){setBusy(true);setError('');try{const r=await apiFetch(path,{method:'POST',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.detail||JSON.stringify(data));if(data.id)watchJob(data.id);else await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function autofit(){await postJob(`/v1/projects/${id}/autofit-timing`)}
 async function safeRender(){setBusy(true);setError('');try{const fit=await apiFetch(`/v1/projects/${id}/autofit-timing`,{method:'POST'});const fitBody=await fit.json();if(!fit.ok)throw new Error(fitBody.detail||JSON.stringify(fitBody));await load();const r=await apiFetch(`/v1/projects/${id}/render`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'preview',quality:'draft'})});const body=await r.json();if(!r.ok)throw new Error(body.detail||JSON.stringify(body));watchJob(body.id)}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function engineHealth(){try{const bridge=await apiFetch('/v1/engine/health');const bridgeBody=await bridge.json();if(!bridge.ok)throw new Error(bridgeBody.detail||JSON.stringify(bridgeBody));const r=await apiFetch('/v1/engine/preflight',{method:'POST'});const body=await r.json();setEngine({bridge:bridgeBody,preflight:body});if(!r.ok)throw new Error(body.detail||JSON.stringify(body))}catch(e){setEngine({status:'error',error:String(e)})}}
 const planner=useMemo(()=>project?.scenes?.[0]?.metadata_json||{},[project]);
 const timingMap=useMemo(()=>Object.fromEntries((timing?.scenes||[]).map(x=>[x.scene_id,x])),[timing]);
 if(!project)return <div className="panel">{error||'Loading project…'}</div>;
 return <>
  <section className="projectStudioHero"><div><div className="heroStatus"><span className={`state state-${project.status.toLowerCase()}`}>{project.status}</span><span>{project.platform}</span><span>{project.aspect_ratio}</span></div><h1>{project.title}</h1><p>{project.prompt}</p></div><div className="creditBadge"><small>Estimated</small><strong>{project.estimated_credits}</strong><span>credits</span></div></section>
  <section className="studioStats"><div><span>Scenes</span><b>{project.scenes.length}</b></div><div><span>Target</span><b>{project.duration_seconds}s</b></div><div><span>Safe timing</span><b className={timing?.status==='RISK'?'red':'green'}>{timing?.status||'—'}</b></div><div><span>Planner</span><b>{planner.planner_provider||'—'}</b></div><div><span>Model</span><b>{planner.planner_model||'—'}</b></div></section>
  <div className="tabs"><button className={tab==='studio'?'active':''} onClick={()=>setTab('studio')}>Studio</button><button className={tab==='media'?'active':''} onClick={()=>setTab('media')}>Media</button><button className={tab==='render'?'active':''} onClick={()=>setTab('render')}>Render</button><button className={tab==='diagnostics'?'active':''} onClick={()=>setTab('diagnostics')}>Diagnostics</button></div>
  {job&&<section className="jobBar"><div><span>{job.stage}</span><b>{job.progress}%</b></div><div className="progress"><i style={{width:`${job.progress}%`}}/></div>{job.error&&<pre className="errorLog">{job.error}</pre>}</section>}
  {error&&<div className="errorBox">{error}</div>}

  {tab==='studio'&&<div className="studioLayout"><main><div className="sectionHead"><div><span className="eyebrow">SCENE EDITOR</span><h2>Edit without rebuilding everything</h2></div><button className="secondaryButton buttonAuto" disabled={busy} onClick={()=>postJob(`/v1/projects/${id}/generate`)}>✦ Regenerate story</button></div>{timing?.status==='RISK'&&<div className="timingBanner"><div><b>Speech timing risk detected</b><span>{timing.total_requested_seconds}s requested → {timing.total_recommended_seconds}s recommended. V6.8 renderer will self-heal and remove oversized tails too, but you can persist safe timing now.</span></div><button disabled={busy} onClick={autofit}>Auto-fit all scenes</button></div>}<div className="sceneList">{project.scenes.map(s=><SceneCard key={s.id} scene={s} timing={timingMap[s.id]} onChanged={load}/>)}</div></main><aside className="storyRail"><div className="railCard"><span className="eyebrow">STORY DNA</span><h3>Hook</h3><p>{planner.story_hook||'Not generated yet'}</p><h3>Running joke</h3><p>{planner.running_joke||'—'}</p><h3>Twist</h3><p>{planner.twist||'—'}</p></div><div className="railCard"><span className="eyebrow">QUICK ACTIONS</span><button disabled={busy||!project.scenes.length} onClick={()=>postJob(`/v1/projects/${id}/media`,{voice:'HindiNeural',speech_rate:185,force:false})}>🧪 Generate storyboard draft</button><button className="secondaryButton" disabled={busy||!project.scenes.length} onClick={()=>setTab('render')}>🎬 Open render controls</button></div></aside></div>}

  {tab==='media'&&<section className="panel"><div className="sectionHead"><div><span className="eyebrow">ASSET LIBRARY</span><h2>Generated media</h2></div><button className="primarySmall" disabled={busy} onClick={()=>postJob(`/v1/projects/${id}/media`,{voice:'HindiNeural',speech_rate:185,force:false})}>Generate / refresh media</button></div>{project.media_assets?.length?<div className="mediaGrid">{project.media_assets.filter(a=>['final_video','scene_video','image','voice'].includes(a.kind)).map(a=><div className="assetCard" key={a.id}><div className="assetMeta"><span>{a.kind}</span><small>{a.provider}</small></div>{a.kind==='image'?<img src={a.url} alt={a.kind}/>:a.kind==='voice'?<audio controls src={a.url}/>:<video controls src={a.url}/>}</div>)}</div>:<div className="emptyState"><h3>No media yet</h3><p>Generate local voice, captions and scene previews first.</p></div>}</section>}

  {tab==='render'&&<section className="renderGrid"><div className="panel"><span className="eyebrow">DRAFT STORYBOARD</span><h2>Static debug preview</h2><p>This is intentionally NOT the real video. It only checks script/captions. Real output uses the 3D renderer.</p><button className="secondaryButton" disabled={busy} onClick={()=>postJob(`/v1/projects/${id}/compose`,{burn_subtitles:true,resolution:project.aspect_ratio==='16:9'?'1280x720':'720x1280'})}>Build storyboard draft</button></div><div className="panel emphasis"><span className="eyebrow">REAL 3D VIDEO</span><h2>Generate animated character preview</h2><p>Default production path: Babuji/Guddu/Bittu 3D characters, colored environment, camera cuts, expressions, body motion and neural Hindi speech. Static cards are not used.</p><div className={engine?.engine_patch?.active?'engineReadyBanner':'engineReadyBanner warn'}><span>{engine?.engine_patch?.active?'✓':'!'}</span><div><strong>{engine?.engine_patch?.active?'3D renderer + neural TTS ready':'3D engine not yet verified'}</strong><small>Bridge {engine?.bridge_version||'—'} • neural voice + adaptive continuity {engine?.engine_patch?.active?'ON':'bridge fallback ON'}</small></div></div><div className="renderSafetyList"><div><span>Persist timing</span><b>Auto</b></div><div><span>Bridge timing</span><b>Adaptive • no 6.5s floor</b></div><div><span>Actual TTS reconciliation</span><b>V6.8 + edge trim</b></div></div><button className="safeRenderButton" disabled={busy} onClick={safeRender}>🎬 Generate REAL 3D preview</button><button className="secondaryButton" disabled={busy} onClick={()=>postJob(`/v1/projects/${id}/render`,{mode:'preview',quality:'draft'})}>Render without persisting timing</button></div><div className="panel"><span className="eyebrow">FINAL</span><h2>Full render</h2><p>Use after the preview passes. Existing engine resume behavior remains preserved.</p><button className="secondaryButton" disabled={busy} onClick={()=>postJob(`/v1/projects/${id}/render`,{mode:'full',quality:'standard'})}>Render full video</button></div>{project.artifacts?.length>0&&<div className="panel renderGallery"><h2>Renders</h2><div className="mediaGrid">{project.artifacts.map(a=><div className="assetCard" key={a.id}><div className="assetMeta"><span>{a.kind}</span></div><video controls src={a.url}/></div>)}</div></div>}</section>}

  {tab==='diagnostics'&&<section className="diagnosticGrid"><div className="panel"><span className="eyebrow">ENGINE HEALTH</span><h2>Host bridge + Blender</h2><button onClick={engineHealth}>Run engine checks</button>{engine&&<pre className="diagnosticLog">{JSON.stringify(engine,null,2)}</pre>}</div><div className="panel"><span className="eyebrow">TIMING REPORT</span><h2>{timing?.status||'—'}</h2><p>Requested {timing?.total_requested_seconds||0}s • recommended {timing?.total_recommended_seconds||0}s</p><div className="timingRows">{timing?.scenes.map(x=><div key={x.scene_id}><span>Scene {x.scene_number}</span><b className={x.status==='RISK'?'red':'green'}>{x.requested_seconds}s → {x.recommended_seconds}s</b></div>)}</div><button className="secondaryButton" onClick={autofit}>Persist safe timing</button></div><div className="panel"><span className="eyebrow">V0.8 AUDIO + MOTION QUALITY</span><h2>Natural continuity guards</h2><ol><li>Adaptive per-turn pauses instead of fixed silence</li><li>TTS leading/trailing silence trim</li><li>Renderer V6.8 grows or shrinks scenes from actual audio</li><li>Room-tone seams + micro J-cuts for continuous dialogue</li><li>Stronger 3-character blocking + text-driven mouth shapes</li></ol><p className="muted">Ordinary unexplained dead-air is capped around 0.45s; longer holds must be an intentional reaction/punch/location transition.</p></div></section>}
 </>
}
